### ISSUE TITLE
Script is too sensetive regarding points at the end of Aphorism number

### ISSUE THREAD

**Issue by HammoodObaid** [UoMResearchIT/CommentaryToEpidoc#11]
I think the following error is caused by the aphorism number not having a fullstop at the end of aphorism number e.g. "3" instead of "3."
Can we make this more lenient? 
Error is from "Galen commentaries book 1"
2017-03-02 14:46:03,054 - hyppocratic.CommentaryToEpidoc - ERROR - aphorism format does not respect the convention. It should be a number following by a point

**Comment by gruel** [comment]
The main problem is not that the script is too sensitive but that the aphorism separation is not consistent. If it was only a missing fullstop. that could be solved but there are other file with other separation.

**Comment by gruel** [comment]
Relaxation done:

accept: 

1. or 1
